---
# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.yml` if it exists.
# No extra steps required.
# Should be used together with `docker-compose -f docker-compose-prod.yml up`
# in production.

version: "3.8"
services:
  postgresql-service:
    container_name: springapp-postgres-prod
    restart: unless-stopped
    env_file:
      - ./src/main/resources/.env
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile

  springapp-service:
    container_name: springapp-prod
    restart: on-failure
    env_file:
      - ./src/main/resources/.env
    build:
      context: .
      dockerfile: docker/springapp/Dockerfile
      target: production
    depends_on:
      - postgresql-service

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
