---
# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. This file is ignoring in production, but been using
# in development with: $ docker-compose up

version: "3.8"
services:
  postgresql-service:
    container_name: springapp-postgres-dev
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=springapp
      - POSTGRES_USER=springapp
      - POSTGRES_PASSWORD=springapp

  springapp-service:
    container_name: springapp-dev
    restart: "no"
    network_mode: host
    build:
      context: .
      dockerfile: docker/springapp/dev/Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/springapp

    depends_on:
      - postgresql-service

  pgadmin4-service:
    image: dpage/pgadmin4
    restart: always
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.pg
      PGADMIN_DEFAULT_PASSWORD: pg
      PGADMIN_LISTEN_PORT: 8000
    depends_on:
      - postgresql-service