---
# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `-f docker-compose.prod.yml`
# in production.

version: "3.8"
services:
  postgresql-service:
    container_name: springapp-postgres-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  springapp-service:
    container_name: springapp-prod
    restart: on-failure
    build:
      context: .
      dockerfile: docker/springapp/prod/Dockerfile.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgresql-service
