---
# Use: `docker-compose -f docker-compose-dev-psql-only up`

version: "3.8"
services:
  postgresql-service:
    container_name: springapp-postgres-dev
    restart: unless-stopped
    env_file:
      - ./src/main/resources/.env
    ports:
      - "5432:5432"
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile

  pgadmin4-service:
    image: dpage/pgadmin4
    restart: always
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.pg
      PGADMIN_DEFAULT_PASSWORD: pg
      PGADMIN_LISTEN_PORT: 8000
    depends_on:
      - postgresql-service
